### ISSUE TITLE
Use a stable branch

### ISSUE THREAD

**Issue by denji** [nginx-modules/docker-nginx-boringssl#10]
Branch: `chromium-stable`
URL: `https://boringssl.googlesource.com/boringssl`
* https://boringssl.googlesource.com/boringssl/+/chromium-stable

**Comment by S8Cloud** [comment]
@denji tried the stable branch with the modification showed in the dockerfile but unable to use tls1.3

https://github.com/nginx-modules/docker-nginx-boringssl/blob/master/mainline/alpine/Dockerfile#L116-L118
