### ISSUE TITLE
OpenSSL library not found error

### ISSUE THREAD

**Issue by onurakman** [nginx-modules/docker-nginx-boringssl#20]
checking for OpenSSL library ...not found
checking for OpenSSL library in /usr/local/ ...not found
checking for OpenSSL library in /usr/pkg/ ...not found
checking for OpenSSL library in /opt/local/ ...not found

./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

**Comment by denji** [comment]
Resolved nginx-modules/docker-nginx-boringssl@bb65b6d
