### ISSUE TITLE
BoringSSL have changed the ".c" file extension to the ".cc" file extension

### ISSUE THREAD

**Issue by iz8mbw** [nginx-modules/docker-nginx-boringssl#7]
Hi.
BoringSSL have changed the ".c" file extension to the ".cc" file extension.
The Dockerfile files (this "https://github.com/nginx-modules/docker-nginx-boringssl/blob/master/stable/alpine/Dockerfile" and this "https://github.com/nginx-modules/docker-nginx-boringssl/blob/master/mainline/alpine/Dockerfile") should be updated in the "sed" command part because they still refer to the ".c" files and not to the new ".cc" files.
Thanks.

**Comment by denji** [comment]
Thank you! I will changed https://github.com/nginx-modules/docker-nginx-boringssl/commit/b10735d4c9aa2f5ff66e5788dcdccf907b8bbeff
* https://boringssl.googlesource.com/boringssl/+/master/ssl/ssl_lib.cc
* https://boringssl.googlesource.com/boringssl/+/master/ssl/s3_lib.cc
